// Implementation file for parser generated by fsyacc
module ParserIfElse
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "ParserIfElse.fsy"


# 9 "ParserIfElse.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | OTHER
  | THEN
  | EXPR
  | ELSE
  | IF
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_OTHER
    | TOKEN_THEN
    | TOKEN_EXPR
    | TOKEN_ELSE
    | TOKEN_IF
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startS
    | NONTERM_S
    | NONTERM_MS
    | NONTERM_US

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | OTHER  -> 0 
  | THEN  -> 1 
  | EXPR  -> 2 
  | ELSE  -> 3 
  | IF  -> 4 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_OTHER 
  | 1 -> TOKEN_THEN 
  | 2 -> TOKEN_EXPR 
  | 3 -> TOKEN_ELSE 
  | 4 -> TOKEN_IF 
  | 7 -> TOKEN_end_of_input
  | 5 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startS 
    | 1 -> NONTERM_S 
    | 2 -> NONTERM_S 
    | 3 -> NONTERM_MS 
    | 4 -> NONTERM_MS 
    | 5 -> NONTERM_US 
    | 6 -> NONTERM_US 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 7 
let _fsyacc_tagOfErrorTerminal = 5

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | OTHER  -> "OTHER" 
  | THEN  -> "THEN" 
  | EXPR  -> "EXPR" 
  | ELSE  -> "ELSE" 
  | IF  -> "IF" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | OTHER  -> (null : System.Object) 
  | THEN  -> (null : System.Object) 
  | EXPR  -> (null : System.Object) 
  | ELSE  -> (null : System.Object) 
  | IF  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us; 65535us; 2us; 65535us; 0us; 1us; 7us; 11us; 3us; 65535us; 0us; 2us; 7us; 3us; 8us; 9us; 3us; 65535us; 0us; 4us; 7us; 4us; 8us; 12us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 4us; 8us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 3us; 1us; 3us; 6us; 1us; 2us; 3us; 3us; 5us; 6us; 3us; 3us; 5us; 6us; 3us; 3us; 5us; 6us; 2us; 3us; 6us; 1us; 3us; 1us; 4us; 1us; 5us; 1us; 6us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 10us; 12us; 16us; 20us; 24us; 27us; 29us; 31us; 33us; |]
let _fsyacc_action_rows = 13
let _fsyacc_actionTableElements = [|2us; 32768us; 0us; 10us; 4us; 5us; 0us; 49152us; 0us; 16385us; 1us; 16385us; 3us; 8us; 0us; 16386us; 1us; 32768us; 2us; 6us; 1us; 32768us; 1us; 7us; 2us; 32768us; 0us; 10us; 4us; 5us; 2us; 32768us; 0us; 10us; 4us; 5us; 0us; 16387us; 0us; 16388us; 0us; 16389us; 0us; 16390us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 5us; 7us; 8us; 10us; 12us; 15us; 18us; 19us; 20us; 21us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 6us; 1us; 4us; 6us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 1us; 2us; 2us; 3us; 3us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 65535us; 16386us; 65535us; 65535us; 65535us; 65535us; 16387us; 16388us; 16389us; 16390us; |]
let _fsyacc_reductions ()  =    [| 
# 97 "ParserIfElse.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startS));
# 106 "ParserIfElse.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'MS)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 19 "ParserIfElse.fsy"
                            1
                   )
# 19 "ParserIfElse.fsy"
                 : int));
# 117 "ParserIfElse.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'US)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 19 "ParserIfElse.fsy"
                                     1
                   )
# 19 "ParserIfElse.fsy"
                 : int));
# 128 "ParserIfElse.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'MS)) in
            let _6 = (let data = parseState.GetInput(6) in (Microsoft.FSharp.Core.Operators.unbox data : 'MS)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 20 "ParserIfElse.fsy"
                                                  1
                   )
# 20 "ParserIfElse.fsy"
                 : 'MS));
# 140 "ParserIfElse.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 20 "ParserIfElse.fsy"
                                                              1
                   )
# 20 "ParserIfElse.fsy"
                 : 'MS));
# 150 "ParserIfElse.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 21 "ParserIfElse.fsy"
                                         1
                   )
# 21 "ParserIfElse.fsy"
                 : 'US));
# 161 "ParserIfElse.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'MS)) in
            let _6 = (let data = parseState.GetInput(6) in (Microsoft.FSharp.Core.Operators.unbox data : 'US)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 21 "ParserIfElse.fsy"
                                                                       1
                   )
# 21 "ParserIfElse.fsy"
                 : 'US));
|]
# 174 "ParserIfElse.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 8;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let S lexer lexbuf : int =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
